import { spacing, typography } from "./sizeThemes";

export const lightTheme = {
  ...spacing,
  ...typography,
  colors: {
    background: "#FFFDFA",
    modalBackground: "#FFFDFA",
    line: "#dee2e6",
    text: "#212529",
    iconColor: "#334155",
    greyBackground: "#e8e9ed",
    greyClickable: "#9ca3af",
    greyDisabled: "#b9bfc8",
    buttonOutline: "#d1d5db",
    primary: "#4D8BFF",
    white: "#FFFDFA",
    black: "#212529",
    danger: "#ef4444",
  },
  projectColors: {
    Red: "#FF3232",
    Orange: "#FF8C42",
    Yellow: "#f6bf26",
    Green: "#2BAF68",
    SeaGreen: "#20B2AA",
    Cyan: "#17A2B8",
    Blue: "#4D8BFF",
    Indigo: "#6E6EFF",
    Purple: "#9D5EFF",
    Pink: "#FF88B1",
  },
  darkMode: false,
};

export const darkTheme = {
  ...spacing,
  ...typography,
  colors: {
    background: "#121212",
    modalBackground: "#212121",
    line: "#3f3f46",
    text: "#FFFDFA",
    iconColor: "#FFFDFA",
    greyBackground: "#374151",
    greyClickable: "#52525b",
    greyDisabled: "#9ca3af",
    buttonOutline: "#d1d5db",
    primary: "#4D8BFF",
    white: "#FFFDFA",
    black: "#212529",
    danger: "#f87171",
  },
  projectColors: {
    Red: "#FF3232",
    Orange: "#FF8C42",
    Yellow: "#f6bf26",
    Green: "#2BAF68",
    SeaGreen: "#20B2AA",
    Cyan: "#17A2B8",
    Blue: "#4D8BFF",
    Indigo: "#6E6EFF",
    Purple: "#9D5EFF",
    Pink: "#FF88B1",
  },
  darkMode: true,
};
